### ISSUE TITLE
Vite Import  Error 2.0.5+

### ISSUE THREAD

**Issue by enchorb** [jannikbuschke/formik-antd#224]
Getting this error from vite after upgrading from `2.0.4` to `2.0.5`

```
 Failed to resolve entry for package "formik-antd". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-scan]
    node_modules/esbuild/lib/main.js:1226:21:
      1226 │         let result = await callback({
           ╵                      ^
    at packageEntryFailure (file:///D:/Code/node_modules/vite/dist/node/chunks/dep-BcnkIxro.js:16287:15)
    at resolvePackageEntry (file:///D:/Code/node_modules/vite/dist/node/chunks/dep-BcnkIxro.js:16284:3)
    at tryNodeResolve (file:///D:/Code/node_modules/vite/dist/node/chunks/dep-BcnkIxro.js:16149:18)
    at ResolveIdContext.resolveId (file:///D:/Code/node_modules/vite/dist/node/chunks/dep-BcnkIxro.js:15934:19)
    at EnvironmentPluginContainer.resolveId (file:///D:/Code/node_modules/vite/dist/node/chunks/dep-BcnkIxro.js:46930:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async resolve (file:///D:/Code/node_modules/vite/dist/node/chunks/dep-BcnkIxro.js:18009:22)
    at async file:///D:/Code/node_modules/vite/dist/node/chunks/dep-BcnkIxro.js:18174:28
    at async requestCallbacks.on-resolve (D:\Code\node_modules\esbuild\lib\main.js:1226:22)
    at async handleRequest (D:\Code\node_modules\esbuild\lib\main.js:647:11)
  This error came from the "onResolve" callback registered here:
    node_modules/esbuild/lib/main.js:1150:20:
      1150 │       let promise = setup({
           ╵                     ^
    at setup (file:///D:/Code/node_modules/vite/dist/node/chunks/dep-BcnkIxro.js:18162:13)
    at handlePlugins (D:\Code\node_modules\esbuild\lib\main.js:1150:21)
    at buildOrContextImpl (D:\Code\node_modules\esbuild\lib\main.js:873:5)
    at Object.buildOrContext (D:\Code\node_modules\esbuild\lib\main.js:699:5)
    at D:\Code\node_modules\esbuild\lib\main.js:2037:68
    at new Promise (<anonymous>)
    at Object.context (D:\Code\node_modules\esbuild\lib\main.js:2037:27)
    at Object.context (D:\Code\node_modules\esbuild\lib\main.js:1879:58)
    at prepareEsbuildScanner (file:///D:/Code/node_modules/vite/dist/node/chunks/dep-BcnkIxro.js:17947:24)
```

**Comment by coozin** [comment]
Possible workaround in the vite config

```
resolve: {
            alias: {
                // Fix for formik-antd 2.0.5 missing es directory
                // The package.json points to "./es/index.js" but the es directory is missing
                'formik-antd': 'formik-antd/lib/index.js',
            },
        },
```
